In [1]:
import tensorflow as tf

Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.


In [3]:
x  = tf.constant([[1,2,3],[4,5,6]])
y  = tf.constant([[1,2,3],[4,5,6]])

In [4]:
z = x- y
print(z)

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


In [5]:
# tensorflow has some features similar with numpy module
a = tf.constant([[2,3],[1,4]], dtype = 'float32',shape = (2,2))

In [6]:
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [1., 4.]], dtype=float32)>

In [7]:
# Build the convolutional neural network
from tensorflow import  keras
from tensorflow.keras import layers 
from tensorflow.keras.datasets import cifar10 
# link explain what is cifar10:  https://g.co/bard/share/81ada258e94e
# note: cifar10 human accuracy is approcimately 94%

In [8]:
#load data 
(x_train, y_train), (x_test, y_test) = cifar10.load_data()
# because its type defeaut is float64 which is unnessary so we need to convert it in to float32

x_train = x_train.astype('float32')/ 255.0
x_test = x_test.astype('float32')/255.0

170498071/170498071 [==============================] - 46s 0us/step


In [11]:
# cool, now lwt buil an actual model

model = keras.Sequential(
    [
        keras.Input(shape=(32,32,3)),
        layers.Conv2D(32, 3, padding = 'valid', activation = 'relu'),
        layers.MaxPooling2D(pool_size=(2,2)), # you don't need to define a pool_size because it is defaut value
        layers.Conv2D(64, 3, activation = 'relu'),
        layers.MaxPooling2D(),
        layers.Conv2D(128,3, activation = 'relu'),
        layers.Flatten(),
        layers.Dense(64, activation = 'relu'),
        layers.Dense(10),
    ]
)

In [12]:
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_1 (Conv2D)           (None, 30, 30, 32)        896       
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 15, 15, 32)        0         
 g2D)                                                            
                                                                 
 conv2d_2 (Conv2D)           (None, 13, 13, 64)        18496     
                                                                 
 max_pooling2d_2 (MaxPoolin  (None, 6, 6, 64)          0         
 g2D)                                                            
                                                                 
 conv2d_3 (Conv2D)           (None, 4, 4, 128)         73856     
                                                                 
 flatten (Flatten)           (None, 2048)             

In [14]:
# compile model
model.compile(
    loss = keras.losses.SparseCategoricalCrossentropy(from_logits = True),
    optimizer=keras.optimizers.Adam(lr = 3e-4),
    metrics = ['Accuracy'],
)

model.fit(x_train, y_train, batch_size = 64, epochs =10 ,  verbose = 2 )
model.evaluate(x_test, y_test, batch_size = 54, verbose = 2)

Epoch 1/10
782/782 - 56s - loss: 1.5289 - Accuracy: 0.4446 - 56s/epoch - 72ms/step
Epoch 2/10
782/782 - 46s - loss: 1.1458 - Accuracy: 0.5948 - 46s/epoch - 58ms/step
Epoch 3/10
782/782 - 46s - loss: 0.9702 - Accuracy: 0.6612 - 46s/epoch - 59ms/step
Epoch 4/10
782/782 - 46s - loss: 0.8645 - Accuracy: 0.7006 - 46s/epoch - 59ms/step
Epoch 5/10
782/782 - 46s - loss: 0.7745 - Accuracy: 0.7316 - 46s/epoch - 59ms/step
Epoch 6/10
782/782 - 45s - loss: 0.7076 - Accuracy: 0.7537 - 45s/epoch - 58ms/step
Epoch 7/10
782/782 - 45s - loss: 0.6411 - Accuracy: 0.7759 - 45s/epoch - 57ms/step
Epoch 8/10
782/782 - 45s - loss: 0.5856 - Accuracy: 0.7963 - 45s/epoch - 58ms/step
Epoch 9/10
782/782 - 46s - loss: 0.5303 - Accuracy: 0.8148 - 46s/epoch - 58ms/step
Epoch 10/10
782/782 - 49s - loss: 0.4810 - Accuracy: 0.8323 - 49s/epoch - 63ms/step
186/186 - 4s - loss: 0.9068 - Accuracy: 0.7092 - 4s/epoch - 20ms/step


[0.9068413972854614, 0.7092000246047974]

In [18]:
# we need to improve this code above,
# let build a fucntional API instead of writing its singularly

def my_model():
    inputs = keras.Input(shape=(32,32,3))
    x = layers.Conv2D(32,3)(inputs)
    x = layers.BatchNormalization()(x)
    x = keras.activations.relu(x)
    x = layers.MaxPooling2D()(x)
    x = layers.Conv2D(64, 5, padding = 'same')(x)
    x = layers.BatchNormalization()(x)
    x = keras.activations.relu(x)

    x = layers.Conv2D(128, 3)(x)
    x = layers.BatchNormalization()(x)
    x = keras.activations.relu(x)
    x = layers.Flatten()(x)
    x = layers.Dense(64, activation = 'relu')(x)
    outputs = layers.Dense(10)(x)
    model = keras.Model(inputs = inputs, outputs = outputs)
    return model

model = my_model()

# compile model
model.compile(
    loss = keras.losses.SparseCategoricalCrossentropy(from_logits = True),
    optimizer=keras.optimizers.Adam(lr = 3e-4),
    metrics = ['Accuracy'],
)

model.fit(x_train, y_train, batch_size = 64, epochs =10 ,  verbose = 2 )
model.evaluate(x_test, y_test, batch_size = 54, verbose = 2)
    

Epoch 1/10
782/782 - 176s - loss: 2.2320 - Accuracy: 0.1643 - 176s/epoch - 226ms/step
Epoch 2/10
782/782 - 175s - loss: 1.9819 - Accuracy: 0.2223 - 175s/epoch - 224ms/step
Epoch 3/10
782/782 - 173s - loss: 1.8695 - Accuracy: 0.2445 - 173s/epoch - 221ms/step
Epoch 4/10
782/782 - 172s - loss: 1.7978 - Accuracy: 0.2601 - 172s/epoch - 220ms/step
Epoch 5/10
782/782 - 168s - loss: 1.7513 - Accuracy: 0.2709 - 168s/epoch - 214ms/step
Epoch 6/10
782/782 - 170s - loss: 1.7085 - Accuracy: 0.2851 - 170s/epoch - 218ms/step
Epoch 7/10
782/782 - 236s - loss: 1.6795 - Accuracy: 0.2948 - 236s/epoch - 302ms/step
Epoch 8/10


KeyboardInterrupt: 